config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get 'home/index'

  resources :users, only: [:edit, :update]

  root 'home#index'
  mount Sidekiq::Web => '/sidekiq'

  resources :rooms do
    put 'start' => 'rooms#start'
  end
end

app/models/room.rb
class Room < ActiveRecord::Base
  validates :title, presence: true
  validates :title, uniqueness: true

  scope :active, -> { where(active: true) }
end

app/models/user.rb
class User < ActiveRecord::Base
  mount_uploader :head, HeadUploader

  def generate_token
    if !self.auth_token || self.auth_token_at < 5.days.ago
      self.auth_token = SecureRandom.urlsafe_base64
      self.auth_token_at = DateTime.now
      save
    end
  end

  def authenticate_token(token)
    if self.auth_token_at && self.auth_token_at < 5.days.ago
      self.auth_token = nil
      self.auth_token_at = nil
      save
    end

    return true if self.auth_token == token
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_filter :authenticate

  private

  def authenticate
    if ENV['PASSWORD'] && controller_name != 'home'
      unless authenticate_with_http_basic { |u, p| p == ENV['PASSWORD'] }
        request_http_basic_authentication
      end
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  layout 'game', only: :show
  before_filter :allow_iframe_requests, only: :show

  def index
    @rooms = Room.all
  end

  def show
    @room = Room.find params[:id]
  end

  def new
    @room = Room.new
  end

  def create
    @room = Room.new room_params

    if @room.save
      redirect_to :rooms
    else
      render :new
    end
  end

  def edit
    @room = Room.find params[:id]
  end

  def update
    @room = Room.find params[:id]

    if @room.update_attributes room_params
      redirect_to :rooms
    else
      render :edit
    end
  end

  def destroy
    room = Room.find params[:id]
    room.destroy

    redirect_to :rooms
  end

  def start
    room = Room.find params[:room_id]

    room.active = !room.active
    room.save

    bot = SlackBot.new(room)
    room.active ? bot.start : bot.stop

    redirect_to edit_room_path(room)
  end

  private

  def room_params
    params.require(:room).permit(:title, :channel)
  end

  def allow_iframe_requests
    response.headers.delete('X-Frame-Options')
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :find_user, :authenticate_user

  def edit
  end

  def update
    if @user.update_attributes(user_params)
      flash[:notice] = 'Your mahvatar has been successfully updated!'
    end

    render :edit
  end

  private
  def user_params
    params.require(:user).permit(:name, :head)
  end

  def find_user
    @user = User.find params[:id]
  end

  def authenticate_user
    if !@user.auth_token_at || @user.auth_token != params[:auth_token]
      render nothing: true, status: :unauthorized
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/home/index.html.erb
<h1>Welcome!</h1>
<p>Mahvatar is a chat based game which is currently in development. It isn't available for public consumption yet but you can check out the code on <%= link_to 'github', 'https://github.com/zoeesilcock/mahvatar' %>. More details to follow.</p>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-inverse">
  <div class="container-fluid">
    <div class="navbar-header">
      <a class="navbar-brand" href="#">mahvatar</a>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>mahvatar</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render partial: 'layouts/navbar' %>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/game.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mahvatar</title>
  <%= stylesheet_link_tag 'game', media: 'all' %>
  <%= javascript_include_tag 'game' %>
  <%= csrf_meta_tags %>
  <script>
  var FIREBASE_URL = "<%= ENV['FIREBASE_URL'] %>";
  </script>
</head>
<body>

<%= yield %>
<div id="screen"></div>

</body>
</html>

app/views/rooms/_form.html.erb
<%= simple_form_for @room do |f| %>
    <%= f.input :title %>
    <%= f.input :channel %>

    <%= f.button :submit, class: 'btn btn-primary pull-right' %>
    <%= yield %>
<% end %>

app/views/rooms/edit.html.erb
<%= render layout: 'form' do %>
    <%= link_to @room.active ? t('.stop') : t('.start'), room_start_path(@room), method: :put, class: 'btn btn-default pull-right' %>
<% end %>

app/views/rooms/index.html.erb
<h1>Welcome!</h1>

<ul>
<% @rooms.each do |room| %>
    <li>
        <%= link_to room.title, room %>
        <%= link_to t('.edit'), edit_room_path(room) %>
        <%= link_to t('.remove'), room_path(room), method: :delete %>
    </li>
<% end %>
</ul>

<%= link_to t('.new'), new_room_path %>

app/views/rooms/new.html.erb
<%= render partial: 'form' %>

app/views/rooms/show.html.erb
<script>
window.onReady(function() {
  game.data.name = "<%= @room.title %>";
});
</script>

app/views/users/edit.html.erb
<%= simple_form_for @user do |f| %>
    <input name="auth_token" type="hidden" value="<%= params[:auth_token] %>" />

    <%= f.input :name %>

    <div class="row">
        <div class="col-xs-6">
            <%= f.input :head %>
        </div>
        <div class="col-xs-6">
            <%= image_tag @user.head.url, class: 'head pull-right' %>
        </div>
    </div>

    <%= f.button :submit, class: 'pull-right btn-primary' %>
<% end %>